### PR TITLE
Test to see if Jenkins approves the tests

### PR DESCRIPTION
**Pull request by ARosenbaum98**

### CODE REVIEW

**Comment by ryanmohler172** [comment]
[48% (-24.05%) vs master 72%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/9/)

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler172** [comment]
[68% (-4.39%) vs master 72%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/10/)

**Comment by ryanmohler17** [comment]
Now it has the correct coverage

**Pull request closed without merging**
