### PR TITLE
Adds tests and functionality to UserServiceImpl.

### PR DESCRIPTION
**Pull request by CJacobJ**
Adds functionality to getAllUsers in UserServiceImpl.
Removes getUserCredentials from UserServiceImpl and UserService due to not being implemented or used.
Adds tests for all UserServiceImpl functions except for createNewUser.

Will add tests for createNewUser after password hashing changes are added.

### CODE REVIEW

**Comment by ryanmohler172** [comment]
[86% (-0.89%) vs master 87%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/50/)

**Comment by CJacobJ** [comment]
Coverage went down? That's wierd.

**Comment by ARosenbaum98** [comment]
Is this supposed to be a draft or do you want to merge into main?

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by CJacobJ** [comment]
I was waiting for #22 to get merged, but since it got closed, I guess this can be merged now.

**Comment by ryanmohler172** [comment]
[95% (+3.87%) vs master 91%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/55/)

**Comment by CJacobJ** [comment]
One minute while I remove the findAll override from the repo

**Comment by ryanmohler172** [comment]
[95% (+3.87%) vs master 91%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/56/)

**Comment by CJacobJ** [comment]
Alright, it's ready

**Review by Johngh17 — APPROVED** [review]

**Comment by ryanmohler172** [comment]
[95% (+3.87%) vs master 91%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/57/)

**Pull request merged**
