### PR TITLE
Adds logs to ValidationServiceImpl

### PR DESCRIPTION
**Pull request by CJacobJ**
Adds logging to ValidationServiceImpl and to ReverseJWT

### CODE REVIEW

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler172** [comment]
[97% (-1.23%) vs master 98%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/62/)

**Review by ARosenbaum98 — APPROVED** [review]

**Comment by ryanmohler172** [comment]
[97% (-1.33%) vs master 99%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/65/)

**Comment by ryanmohler172** [comment]
[97% (-1.18%) vs master 99%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/66/)

**Comment by ryanmohler172** [comment]
[98% (+0.31%) vs master 97%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/69/)

**Pull request merged**
