### PR TITLE
Adds logs to UserServiceImpl

### PR DESCRIPTION
**Pull request by CJacobJ**

### CODE REVIEW

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler172** [comment]
[97% (-1.33%) vs master 98%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/61/)

**Review by ARosenbaum98 — APPROVED** [review]

**Pull request merged**
