### PR TITLE
Adds logging to InHouseVariablesService

### PR DESCRIPTION
**Pull request by CJacobJ**
Small one this time

### CODE REVIEW

**Comment by ryanmohler17** [comment]
jenkins build

**Review by ARosenbaum98 — APPROVED** [review]

**Comment by ryanmohler172** [comment]
[97% (-1.68%) vs master 99%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/63/)

**Comment by ryanmohler172** [comment]
[97% (-1.49%) vs master 99%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/67/)

**Comment by ryanmohler172** [comment]
[97% (+0.05%) vs master 97%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/70/)

**Comment by ryanmohler172** [comment]
[98% (+0.04%) vs master 98%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/71/)

**Pull request merged**
