### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by ARosenbaum98**
Lets see if this works as a true request rather than a draft

### CODE REVIEW

**Comment by ryanmohler17** [comment]
Nope, I'll look into it tomorrow morning

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
Ok a restart fixed it

**Comment by ryanmohler172** [comment]
[48% (-23.68%) vs master 72%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/11/)

**Comment by ryanmohler17** [comment]
And it's giving the wrong coverage type again
jenkins build

**Comment by ryanmohler172** [comment]
[48% (-23.68%) vs master 72%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/12/)

**Comment by ryanmohler17** [comment]
Or nvm it only had 48% coverage

**Comment by ARosenbaum98** [comment]
It has 70% coverage on my end. I think that it's not ignoring Lombok and @Generated maybe?

**Comment by ryanmohler17** [comment]
Should ignore generated, maybe not lombok

**Comment by ryanmohler172** [comment]
[74% (+1.94%) vs master 72%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/13/)

**Pull request closed without merging**
