### PR TITLE
Changes to validation

### PR DESCRIPTION
**Pull request by CJacobJ**
When validating jwts, checks if the mentioned user actually exists.

Also adds a new CredentialsInvalid RuntimeException and replaces Exception with it in validateCredentials.

### CODE REVIEW

**Comment by CJacobJ** [comment]
Looks like Jenkins isn't seeing the tests for some reason

**Comment by CJacobJ** [comment]
Actually might be something with the JAVA_HOME env var

**Comment by ryanmohler17** [comment]
Yegh it's a bit broken atm, give me a min.

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler172** [comment]
[84% (+5.95%) vs master 78%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/30/)

**Comment by ryanmohler17** [comment]
Fixed it

**Comment by CJacobJ** [comment]
Thanks!

**Review by ARosenbaum98 — APPROVED** [review]

**Comment by ryanmohler172** [comment]
[79% (+5.64%) vs master 73%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/33/)

**Pull request merged**
