### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by ARosenbaum98**

### CODE REVIEW

**Comment by ryanmohler172** [comment]
[76% (+1.86%) vs master 74%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/15/)

**Comment by ryanmohler172** [comment]
[76% (+1.86%) vs master 74%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/16/)

**Comment by ryanmohler172** [comment]
[81% (+7.06%) vs master 74%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/17/)

**Comment by ryanmohler172** [comment]
[81% (+7.06%) vs master 74%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/18/)

**Review by Johngh17 — APPROVED** [review]

**Pull request merged**
