### PR TITLE
Adds more logs to the controllers

### PR DESCRIPTION
**Pull request by CJacobJ**
Adds more logs to the controllers, makes some logs more detailed.

### CODE REVIEW

**Review by ARosenbaum98 — APPROVED** [review]

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler172** [comment]
[97% (-1.47%) vs master 99%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/64/)

**Comment by ryanmohler172** [comment]
[97% (-1.3%) vs master 99%](http://3.91.248.52:8080/jenkins/job/User-Service%20-%20PR/68/)

**Pull request merged**
